//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGIS.WebGISService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KY_PendingWork", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KY_PendingWork : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkTypeField;
        
        private int WorkCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WorkType {
            get {
                return this.WorkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkTypeField, value) != true)) {
                    this.WorkTypeField = value;
                    this.RaisePropertyChanged("WorkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int WorkCount {
            get {
                return this.WorkCountField;
            }
            set {
                if ((this.WorkCountField.Equals(value) != true)) {
                    this.WorkCountField = value;
                    this.RaisePropertyChanged("WorkCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkName {
            get {
                return this.WorkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkNameField, value) != true)) {
                    this.WorkNameField = value;
                    this.RaisePropertyChanged("WorkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WorkURL {
            get {
                return this.WorkURLField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkURLField, value) != true)) {
                    this.WorkURLField = value;
                    this.RaisePropertyChanged("WorkURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rtimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rtime {
            get {
                return this.rtimeField;
            }
            set {
                if ((object.ReferenceEquals(this.rtimeField, value) != true)) {
                    this.rtimeField = value;
                    this.RaisePropertyChanged("rtime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebGISService.WebGISServiceSoap")]
    public interface WebGISServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KY_GetPendingWork", ReplyAction="*")]
        WebGIS.WebGISService.KY_GetPendingWorkResponse KY_GetPendingWork(WebGIS.WebGISService.KY_GetPendingWorkRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sysflag 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XD_lockOrder", ReplyAction="*")]
        WebGIS.WebGISService.XD_lockOrderResponse XD_lockOrder(WebGIS.WebGISService.XD_lockOrderRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sysflag 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XD_queryStatusOrder", ReplyAction="*")]
        WebGIS.WebGISService.XD_queryStatusOrderResponse XD_queryStatusOrder(WebGIS.WebGISService.XD_queryStatusOrderRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sysflag 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XD_activateOrder", ReplyAction="*")]
        WebGIS.WebGISService.XD_activateOrderResponse XD_activateOrder(WebGIS.WebGISService.XD_activateOrderRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sysflag 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XD_setParamOrder", ReplyAction="*")]
        WebGIS.WebGISService.XD_setParamOrderResponse XD_setParamOrder(WebGIS.WebGISService.XD_setParamOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KY_GetPendingWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KY_GetPendingWork", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.KY_GetPendingWorkRequestBody Body;
        
        public KY_GetPendingWorkRequest() {
        }
        
        public KY_GetPendingWorkRequest(WebGIS.WebGISService.KY_GetPendingWorkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KY_GetPendingWorkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public KY_GetPendingWorkRequestBody() {
        }
        
        public KY_GetPendingWorkRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KY_GetPendingWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KY_GetPendingWorkResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.KY_GetPendingWorkResponseBody Body;
        
        public KY_GetPendingWorkResponse() {
        }
        
        public KY_GetPendingWorkResponse(WebGIS.WebGISService.KY_GetPendingWorkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KY_GetPendingWorkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebGIS.WebGISService.KY_PendingWork[] KY_GetPendingWorkResult;
        
        public KY_GetPendingWorkResponseBody() {
        }
        
        public KY_GetPendingWorkResponseBody(WebGIS.WebGISService.KY_PendingWork[] KY_GetPendingWorkResult) {
            this.KY_GetPendingWorkResult = KY_GetPendingWorkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_lockOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_lockOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_lockOrderRequestBody Body;
        
        public XD_lockOrderRequest() {
        }
        
        public XD_lockOrderRequest(WebGIS.WebGISService.XD_lockOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_lockOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysflag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long tno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int orderType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int lockType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public uint torque;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public uint rotspeed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string lockreason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string unlockreason;
        
        public XD_lockOrderRequestBody() {
        }
        
        public XD_lockOrderRequestBody(string sysflag, long cid, long tno, int orderType, int lockType, uint torque, uint rotspeed, string lockreason, string unlockreason) {
            this.sysflag = sysflag;
            this.cid = cid;
            this.tno = tno;
            this.orderType = orderType;
            this.lockType = lockType;
            this.torque = torque;
            this.rotspeed = rotspeed;
            this.lockreason = lockreason;
            this.unlockreason = unlockreason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_lockOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_lockOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_lockOrderResponseBody Body;
        
        public XD_lockOrderResponse() {
        }
        
        public XD_lockOrderResponse(WebGIS.WebGISService.XD_lockOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_lockOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebGIS.WebGISService.ResponseResult XD_lockOrderResult;
        
        public XD_lockOrderResponseBody() {
        }
        
        public XD_lockOrderResponseBody(WebGIS.WebGISService.ResponseResult XD_lockOrderResult) {
            this.XD_lockOrderResult = XD_lockOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_queryStatusOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_queryStatusOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_queryStatusOrderRequestBody Body;
        
        public XD_queryStatusOrderRequest() {
        }
        
        public XD_queryStatusOrderRequest(WebGIS.WebGISService.XD_queryStatusOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_queryStatusOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysflag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long tno;
        
        public XD_queryStatusOrderRequestBody() {
        }
        
        public XD_queryStatusOrderRequestBody(string sysflag, long cid, long tno) {
            this.sysflag = sysflag;
            this.cid = cid;
            this.tno = tno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_queryStatusOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_queryStatusOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_queryStatusOrderResponseBody Body;
        
        public XD_queryStatusOrderResponse() {
        }
        
        public XD_queryStatusOrderResponse(WebGIS.WebGISService.XD_queryStatusOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_queryStatusOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebGIS.WebGISService.ResponseResult XD_queryStatusOrderResult;
        
        public XD_queryStatusOrderResponseBody() {
        }
        
        public XD_queryStatusOrderResponseBody(WebGIS.WebGISService.ResponseResult XD_queryStatusOrderResult) {
            this.XD_queryStatusOrderResult = XD_queryStatusOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_activateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_activateOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_activateOrderRequestBody Body;
        
        public XD_activateOrderRequest() {
        }
        
        public XD_activateOrderRequest(WebGIS.WebGISService.XD_activateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_activateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysflag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long tno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string energytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int orderType;
        
        public XD_activateOrderRequestBody() {
        }
        
        public XD_activateOrderRequestBody(string sysflag, long cid, long tno, string vin, string energytype, int orderType) {
            this.sysflag = sysflag;
            this.cid = cid;
            this.tno = tno;
            this.vin = vin;
            this.energytype = energytype;
            this.orderType = orderType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_activateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_activateOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_activateOrderResponseBody Body;
        
        public XD_activateOrderResponse() {
        }
        
        public XD_activateOrderResponse(WebGIS.WebGISService.XD_activateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_activateOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebGIS.WebGISService.ResponseResult XD_activateOrderResult;
        
        public XD_activateOrderResponseBody() {
        }
        
        public XD_activateOrderResponseBody(WebGIS.WebGISService.ResponseResult XD_activateOrderResult) {
            this.XD_activateOrderResult = XD_activateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_setParamOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_setParamOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_setParamOrderRequestBody Body;
        
        public XD_setParamOrderRequest() {
        }
        
        public XD_setParamOrderRequest(WebGIS.WebGISService.XD_setParamOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_setParamOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysflag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long tno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string datevalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dayvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string minutevalue;
        
        public XD_setParamOrderRequestBody() {
        }
        
        public XD_setParamOrderRequestBody(string sysflag, long cid, long tno, string datevalue, string dayvalue, string minutevalue) {
            this.sysflag = sysflag;
            this.cid = cid;
            this.tno = tno;
            this.datevalue = datevalue;
            this.dayvalue = dayvalue;
            this.minutevalue = minutevalue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XD_setParamOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XD_setParamOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGIS.WebGISService.XD_setParamOrderResponseBody Body;
        
        public XD_setParamOrderResponse() {
        }
        
        public XD_setParamOrderResponse(WebGIS.WebGISService.XD_setParamOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XD_setParamOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebGIS.WebGISService.ResponseResult XD_setParamOrderResult;
        
        public XD_setParamOrderResponseBody() {
        }
        
        public XD_setParamOrderResponseBody(WebGIS.WebGISService.ResponseResult XD_setParamOrderResult) {
            this.XD_setParamOrderResult = XD_setParamOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebGISServiceSoapChannel : WebGIS.WebGISService.WebGISServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebGISServiceSoapClient : System.ServiceModel.ClientBase<WebGIS.WebGISService.WebGISServiceSoap>, WebGIS.WebGISService.WebGISServiceSoap {
        
        public WebGISServiceSoapClient() {
        }
        
        public WebGISServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebGISServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebGISServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebGISServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGIS.WebGISService.KY_GetPendingWorkResponse WebGIS.WebGISService.WebGISServiceSoap.KY_GetPendingWork(WebGIS.WebGISService.KY_GetPendingWorkRequest request) {
            return base.Channel.KY_GetPendingWork(request);
        }
        
        public WebGIS.WebGISService.KY_PendingWork[] KY_GetPendingWork(string username, string password) {
            WebGIS.WebGISService.KY_GetPendingWorkRequest inValue = new WebGIS.WebGISService.KY_GetPendingWorkRequest();
            inValue.Body = new WebGIS.WebGISService.KY_GetPendingWorkRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebGIS.WebGISService.KY_GetPendingWorkResponse retVal = ((WebGIS.WebGISService.WebGISServiceSoap)(this)).KY_GetPendingWork(inValue);
            return retVal.Body.KY_GetPendingWorkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGIS.WebGISService.XD_lockOrderResponse WebGIS.WebGISService.WebGISServiceSoap.XD_lockOrder(WebGIS.WebGISService.XD_lockOrderRequest request) {
            return base.Channel.XD_lockOrder(request);
        }
        
        public WebGIS.WebGISService.ResponseResult XD_lockOrder(string sysflag, long cid, long tno, int orderType, int lockType, uint torque, uint rotspeed, string lockreason, string unlockreason) {
            WebGIS.WebGISService.XD_lockOrderRequest inValue = new WebGIS.WebGISService.XD_lockOrderRequest();
            inValue.Body = new WebGIS.WebGISService.XD_lockOrderRequestBody();
            inValue.Body.sysflag = sysflag;
            inValue.Body.cid = cid;
            inValue.Body.tno = tno;
            inValue.Body.orderType = orderType;
            inValue.Body.lockType = lockType;
            inValue.Body.torque = torque;
            inValue.Body.rotspeed = rotspeed;
            inValue.Body.lockreason = lockreason;
            inValue.Body.unlockreason = unlockreason;
            WebGIS.WebGISService.XD_lockOrderResponse retVal = ((WebGIS.WebGISService.WebGISServiceSoap)(this)).XD_lockOrder(inValue);
            return retVal.Body.XD_lockOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGIS.WebGISService.XD_queryStatusOrderResponse WebGIS.WebGISService.WebGISServiceSoap.XD_queryStatusOrder(WebGIS.WebGISService.XD_queryStatusOrderRequest request) {
            return base.Channel.XD_queryStatusOrder(request);
        }
        
        public WebGIS.WebGISService.ResponseResult XD_queryStatusOrder(string sysflag, long cid, long tno) {
            WebGIS.WebGISService.XD_queryStatusOrderRequest inValue = new WebGIS.WebGISService.XD_queryStatusOrderRequest();
            inValue.Body = new WebGIS.WebGISService.XD_queryStatusOrderRequestBody();
            inValue.Body.sysflag = sysflag;
            inValue.Body.cid = cid;
            inValue.Body.tno = tno;
            WebGIS.WebGISService.XD_queryStatusOrderResponse retVal = ((WebGIS.WebGISService.WebGISServiceSoap)(this)).XD_queryStatusOrder(inValue);
            return retVal.Body.XD_queryStatusOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGIS.WebGISService.XD_activateOrderResponse WebGIS.WebGISService.WebGISServiceSoap.XD_activateOrder(WebGIS.WebGISService.XD_activateOrderRequest request) {
            return base.Channel.XD_activateOrder(request);
        }
        
        public WebGIS.WebGISService.ResponseResult XD_activateOrder(string sysflag, long cid, long tno, string vin, string energytype, int orderType) {
            WebGIS.WebGISService.XD_activateOrderRequest inValue = new WebGIS.WebGISService.XD_activateOrderRequest();
            inValue.Body = new WebGIS.WebGISService.XD_activateOrderRequestBody();
            inValue.Body.sysflag = sysflag;
            inValue.Body.cid = cid;
            inValue.Body.tno = tno;
            inValue.Body.vin = vin;
            inValue.Body.energytype = energytype;
            inValue.Body.orderType = orderType;
            WebGIS.WebGISService.XD_activateOrderResponse retVal = ((WebGIS.WebGISService.WebGISServiceSoap)(this)).XD_activateOrder(inValue);
            return retVal.Body.XD_activateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGIS.WebGISService.XD_setParamOrderResponse WebGIS.WebGISService.WebGISServiceSoap.XD_setParamOrder(WebGIS.WebGISService.XD_setParamOrderRequest request) {
            return base.Channel.XD_setParamOrder(request);
        }
        
        public WebGIS.WebGISService.ResponseResult XD_setParamOrder(string sysflag, long cid, long tno, string datevalue, string dayvalue, string minutevalue) {
            WebGIS.WebGISService.XD_setParamOrderRequest inValue = new WebGIS.WebGISService.XD_setParamOrderRequest();
            inValue.Body = new WebGIS.WebGISService.XD_setParamOrderRequestBody();
            inValue.Body.sysflag = sysflag;
            inValue.Body.cid = cid;
            inValue.Body.tno = tno;
            inValue.Body.datevalue = datevalue;
            inValue.Body.dayvalue = dayvalue;
            inValue.Body.minutevalue = minutevalue;
            WebGIS.WebGISService.XD_setParamOrderResponse retVal = ((WebGIS.WebGISService.WebGISServiceSoap)(this)).XD_setParamOrder(inValue);
            return retVal.Body.XD_setParamOrderResult;
        }
    }
}
