//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGIS.SmsSendService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pushservice/", ConfigurationName="SmsSendService.SendSMS")]
    public interface SendSMS {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WebGIS.SmsSendService.SendToPhoneResponse SendToPhone(WebGIS.SmsSendService.SendToPhone request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToPhone {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToPhone", Namespace="http://pushservice/", Order=0)]
        public WebGIS.SmsSendService.SendToPhoneBody Body;
        
        public SendToPhone() {
        }
        
        public SendToPhone(WebGIS.SmsSendService.SendToPhoneBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendToPhoneBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SendToPhoneBody() {
        }
        
        public SendToPhoneBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToPhoneResponse", Namespace="http://pushservice/", Order=0)]
        public WebGIS.SmsSendService.SendToPhoneResponseBody Body;
        
        public SendToPhoneResponse() {
        }
        
        public SendToPhoneResponse(WebGIS.SmsSendService.SendToPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendToPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SendToPhoneResponseBody() {
        }
        
        public SendToPhoneResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSChannel : WebGIS.SmsSendService.SendSMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSClient : System.ServiceModel.ClientBase<WebGIS.SmsSendService.SendSMS>, WebGIS.SmsSendService.SendSMS {
        
        public SendSMSClient() {
        }
        
        public SendSMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGIS.SmsSendService.SendToPhoneResponse WebGIS.SmsSendService.SendSMS.SendToPhone(WebGIS.SmsSendService.SendToPhone request) {
            return base.Channel.SendToPhone(request);
        }
        
        public string SendToPhone(string arg0) {
            WebGIS.SmsSendService.SendToPhone inValue = new WebGIS.SmsSendService.SendToPhone();
            inValue.Body = new WebGIS.SmsSendService.SendToPhoneBody();
            inValue.Body.arg0 = arg0;
            WebGIS.SmsSendService.SendToPhoneResponse retVal = ((WebGIS.SmsSendService.SendSMS)(this)).SendToPhone(inValue);
            return retVal.Body.@return;
        }
    }
}
